apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
  labels:
    app: my-node-app
spec:
  selector:
    app: my-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort # Or LoadBalancer if supported by your cluster
